# Семинар 2: Библиотека Numpy
### Практикум кафедры ММП ВМК МГУ

О чём можно узнать из этого ноутбука:

* операции при работе с массивами
* многомерные массивы
* изменение размеров массивов
* broadcasting
* продвинутая индексация
* view и копирование
* свёртка
* разные прикладные задачи

## Введение в Python

Чтобы подробнее ознакомиться с языком Python, просмотрите ноутбук **intro_to_python**. В этом ноутбуке мы напомним основные понятия, которые пригодятся на этом занятии.


<font color='brown'>**Задача 1.** Задайте матрицу `list_matrix` размером 500 на 10, в которой ij-ый элемент будет равен 10 * i + j. Не используйте библиотеку numpy! </font>

In [1]:
## your code

Проверьте себя:

In [ ]:
assert len(list_matrix) == 500
assert len(list_matrix[0]) == 10
assert list_matrix[10][3] == 103

## Проблемы списков при матричных операциях

Одна из проблем списков — отсутствие поэлементных и матричных операций.

Получим новую матрицу, равную `list_matrix`, умноженной на 2. Измерим время выполнения с помощью магической команды %%timeit:

In [ ]:
%%timeit

new_list_matrix = []

for x_vector in list_matrix:
    new_inner = []
    for xy_element in x_vector:
        new_inner.append(xy_element * 2)
    new_list_matrix.append(new_inner)

А теперь попробуем воспользоваться массивами из библиотеки numpy для аналогичных операций:

In [2]:
# from numpy import * -- НЕ ДЕЛАЙТЕ ТАК
import numpy as np

Текущая версия:

In [28]:
np.__version__

'1.14.2'

С помощью np.zeros зададим нулевой массив нужного размера. Заполним так же, как и list_matrix.

In [3]:
array_matrix = np.zeros((500, 10))

for i in range(500):
    for j in range(10):
        array_matrix[i][j] = j + 10*i
array_matrix[:5]

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.]])

Скоро мы научимся легко использовать конструкции типа:

In [13]:
np.arange(10) + np.arange(0, 41, 10)[:, np.newaxis]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

Все операции с numpy.ndarray по умолчанию поэлементные. Таким образом, умножение на два это всего лишь:

In [4]:
new_array_matrix = 2 * array_matrix

Измерим время выполнения:

In [5]:
%%timeit

new_array_matrix = 2 * array_matrix

4.32 µs ± 220 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Быстрее больше чем в 100 раз...

## Базовые операции

### Создание массивов

Ещё раз обсудим создание массивов. Создание нулевого вектора:

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

**Внимание**. Если размерность массива > 1, размер подаётся в функцию инициализации через кортеж, а не отдельными аргументами!

Для одномерного массива тоже можно писать кортеж:

In [2]:
np.zeros((5, ))

array([0., 0., 0., 0., 0.])

Так правильно:

In [7]:
np.zeros((5, 7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

Так неправильно:

In [8]:
np.zeros(5, 7)

TypeError: data type not understood

Массив из единиц:

In [44]:
np.ones((1, 3))

array([[1., 1., 1.]])

Создание массива последовательных чисел:

In [45]:
# похоже на range, но все числа хранятся в памяти
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Создание массива из Python-объекта:

In [46]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

Вывести размер полученного массива можно с помощью метода shape:

In [47]:
x.shape

(2, 3)

<font color='brown'>**Задача 2.** Задайте массив `result` размером 50 на 30, состоящий из троек.</font>

In [48]:
## your code here

Проверьте себя:

In [ ]:
assert result.shape == (50, 30)
assert np.all(result == 3)

<font color='brown'>**Задача 3.** Какая размерность будет у массива, полученного с помощью команды `np.array([[1], [2]])`?</font>

In [51]:
## your answer here

Можно создать массив из 0, 1 или любого числа, который по размеру равен какому-то другому:

In [12]:
template = np.array([[4, 5, 6], [1, 2, 3], [7, 8, 9], [10, 11, 12]])
template.shape

(4, 3)

In [13]:
np.zeros_like(template)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [24]:
np.ones_like(template)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
np.full_like(template, 42)

array([[42., 42., 42.],
       [42., 42., 42.],
       [42., 42., 42.],
       [42., 42., 42.]])

### Поэлементные операции

In [33]:
x = np.arange(10)
y = np.arange(5, 15)

Поэлементные арифметическии операции:

In [16]:
x + y

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [17]:
x * y

array([  0,   6,  14,  24,  36,  50,  66,  84, 104, 126])

In [18]:
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [34]:
y / x

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 6.        , 3.5       , 2.66666667, 2.25      ,
       2.        , 1.83333333, 1.71428571, 1.625     , 1.55555556])

Поэлементые операции сравнения:

In [19]:
x > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

### Агрегирующие операции

Агрегация булевого массива
* all — все элементы удовлетворяют требованию
* any — хотя бы один элемент удовлетворяет требованию

In [20]:
np.all(x > 5)

False

In [21]:
np.any(x > 5)

True

Нахождение максимума в массиве:

In [22]:
np.max(y)

14

Нахождение позиции максимума:

In [23]:
np.argmax(y)

9

Суммирование всех элементов:

In [24]:
np.sum(x)

45

У многих функций в numpy есть "аналогичный" по принципу работы метод: 

In [25]:
x.sum()

45

In [26]:
y.argmax()

9

### Типы и преобразование типов

Атрибут .dtype хранит информацию о типе массива:

In [27]:
x = np.arange(15)
x.dtype

dtype('int64')

In [28]:
y = np.array([1.5, 2.5])
y.dtype

dtype('float64')

Преобразование типов осуществляется с помощью метода .astype:

In [29]:
x = x.astype(np.float64)
x.dtype

dtype('float64')

Можно сразу указывать желаемый тип при создании массивов при помощи параметра dtype:

In [29]:
np.ones((2, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [30]:
np.ones((2, 3), dtype=str)

array([['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

Подробнее о параметрах и действии функции можно посмотреть при помощи ?:

In [31]:
np.ones?

### Повторение массивов

Чтобы построить двумерный массив, состоящий из повторений одномерных, можно использовать np.tile:

In [146]:
a = np.array([2, 3, 4])
np.tile(a[np.newaxis, :], (2, 1))

array([[2, 3, 4],
       [2, 3, 4]])

In [147]:
np.tile(a, (2, 1))

array([[2, 3, 4],
       [2, 3, 4]])

In [148]:
np.tile(a[:, np.newaxis], 2)

array([[2, 2],
       [3, 3],
       [4, 4]])

## Размеры массивов

### Изменение размера массивов

NumPy массивы всегда лежат в памяти последовательно, одним куском. Поэтому у массива можно изменять размер практически бесплатно.

In [36]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
x.reshape?

In [31]:
x.shape

(2, 3)

"Вытянуть" массив в вектор можно с помощью метода .ravel:

In [32]:
x = x.ravel()
x

array([1, 2, 3, 4, 5, 6])

Изменить размер массива можно с помощью метда .reshape:

In [33]:
new_x = x.reshape(2, 3) # или x.reshape((2, 3))
new_x

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
new_x.shape

(2, 3)

In [35]:
x.shape

(6,)

Можно "не заполнять" одну размерность итогового массива, она заполнится автоматически:

In [36]:
x.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

**Это интересно.** Есть два распространённых способа упорядочить многомерный массив:
* C-order, **по умолчанию в NumPy**. Быстрее всего изменяется последний индекс. Для матриц — сначала идём по столбцам.
* Fortran-order (F-order). Быстрее всего изменяется первый индекс. Для матриц — сначала идём по строкам.

Порядок можно задать с помощью параметра `order` в методе reshape.

In [37]:
x.reshape(2, 3, order='F')

array([[1, 3, 5],
       [2, 4, 6]])

### Фиктивная размерность

Два способа добавить фиктивную размерность в массив:

In [38]:
x[:, np.newaxis] # Эквивалентно x[:, None]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [39]:
x.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

Зачем нужно добавлять фиктивную размерность? Например, чтобы проводить различные операции с массивами неравного размера.

### Broadcasting

Подробное описание: http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

Пусть нам дана матрица $X$ размером $10 \times 10$ и вектор $y$ длины 10. Пусть мы хотим прибавить вектор к каждой строке матрицы. 

In [40]:
x = np.arange(100).reshape(10, 10)
y = np.arange(10)

In [41]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [42]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Наивный способ решения проблемы будет работать правильно!

In [43]:
x + y

array([[  0,   2,   4,   6,   8,  10,  12,  14,  16,  18],
       [ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28],
       [ 20,  22,  24,  26,  28,  30,  32,  34,  36,  38],
       [ 30,  32,  34,  36,  38,  40,  42,  44,  46,  48],
       [ 40,  42,  44,  46,  48,  50,  52,  54,  56,  58],
       [ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68],
       [ 60,  62,  64,  66,  68,  70,  72,  74,  76,  78],
       [ 70,  72,  74,  76,  78,  80,  82,  84,  86,  88],
       [ 80,  82,  84,  86,  88,  90,  92,  94,  96,  98],
       [ 90,  92,  94,  96,  98, 100, 102, 104, 106, 108]])

**Почему?** Правила broadcasting (приведение размеров).

1. Если два массива имеют размерности (a_1, a_2 .. a_n) и (b_1, b_2 .. b_n) соответственно, то между ними можно проводить поэлементные операции, если для каждого i выполнено одно из трёх условий:
    * a_i = b_i
    * a_i = 1
    * b_i = 1
    
2. Если поэлементная операция выполняется между массивами разного размера, то к массиву меньшего размера добавляются ведущие фиктивные размерности.

**Всегда проверяйте операции с броадкастингом! Легко можно напороться на неприятности**

<font color='brown'>**Задача 4.** Какие из этих команд будут выполняться с ошибкой?</font>

1. `np.ones((2, 3)) + np.ones(3)`

2. `np.ones(2) + np.ones((2, 3))`

3. `np.zeros((4, 3)) + np.ones((4, 1))`

4. `np.zeros((3, 4)) + np.ones((4, 3))`

5. `np.zeros((1, 3, 5)) + np.zeros((1, 3))`

6. `np.zeros((5, 3, 1)) + np.zeros((1, 5))`

In [ ]:
## your answer here

<font color='brown'>**Задача 5.** Пусть нам дана матрица $X$ размером $10 \times 10$ и вектор-столбец $y$ длины 10. Получите матрицу result, полученную прибавлением к каждому столбцу $X$ вектора $y$ (без использования циклов). </font>

In [45]:
x = np.arange(100).reshape(10, 10)
y = np.arange(10)

In [52]:
## your code here

Проверьте себя:

In [53]:
assert result[0][0] == 0
for i in range(1, 10):
    assert result[i][i-1] == 10 * i + (i - 1) * 2 + 1

## Матричные операции

In [260]:
x = np.array([[1, 2], [2, 1], [2, 3]])
x

array([[1, 2],
       [2, 1],
       [2, 3]])

Транспонирование:

In [261]:
x.T

array([[1, 2, 2],
       [2, 1, 3]])

Матричное умножение:

In [262]:
y = np.array([[0, 1, 0], [1, 0, 1]])

In [276]:
res = np.dot(x, y)
res

array([[2, 1, 2],
       [1, 2, 1],
       [3, 2, 3]])

### Операции с размерностями

Некоторые из операций можно принять вдоль некоторых размерностей.

Максимум в каждом столбцe (первая размерность, axis=0):

In [279]:
res

array([[2, 1, 2],
       [1, 2, 1],
       [3, 2, 3]])

In [ ]:
np.max(res, axis=0)

In [282]:
res.sum(axis=1)

array([5, 4, 8])

Как легко запомнить, как работает axis:
* после применения функции получится массив, в котором будет отсутствовать размерность указанная в axis, но остальные размерности будут иметь такие же значения

<font color='brown'>**Задача 6.** Дан вектор $x$ и квадратная матрица $A$. Вычислить вектор значений $y_j = argmin_i (x_i + A_{ij})$. </font>

In [348]:
x = np.array([5, 2, 3, 1])
A = np.array([
    [1, 2, 3],
    [2, 2, 4],
    [5, 6, 1],
    [2, 4, 5]
])

In [349]:
## your code

Проверьте себя:

In [354]:
assert y.tolist() == [3, 1, 2]

### Конкатенация матриц

In [57]:
x = np.array([[1, 2], [5, 6]])
y = np.array([[3, 4], [2, 3]])

Конкатенация матриц по горизонтали:

In [399]:
np.hstack((x, y))

array([[1, 2, 3, 4],
       [5, 6, 2, 3]])

Конкатенация матриц по вертикали:

In [400]:
np.vstack((x, y))

array([[1, 2],
       [5, 6],
       [3, 4],
       [2, 3]])

Регулируемая конкатенация по какой-то оси:

In [58]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [5, 6],
       [3, 4],
       [2, 3]])

### Логические маски

Использование масок:

In [500]:
x = np.array([1, 0, 2, 1])

In [360]:
mask = x == 1
mask

array([ True, False, False,  True])

С помощью булевых масок можно выбирать соответствующие элементы массива и даже изменять их:

In [362]:
x[mask]

array([1, 1])

In [364]:
x[mask] = -1
x

array([-1,  0,  2, -1])

С булевыми массивами можно делать побитовые операции с помощью операндов &, |.

С помощью оператора where, можно находить индексы элементов, заданные маской:

In [501]:
np.where(x > 0)

(array([0, 2, 3]),)

В случае одномерного массива np.where возвращается tuple. Подробнее смотри документацию.

<font color='brown'> **Задача 7.** Даны два вектора одинаковой длины: a и b. Оставить в этих векторах только те элементы, которые соответствуют позициям ненулевых элементов в обоих векторах. </font>

In [368]:
a = np.array([0, 1, 0, 2, 3])
b = np.array([1, 5, 2, 0, 6])

In [369]:
## your code here

Проверьте себя:

In [371]:
assert a.tolist() == [1, 3]
assert b.tolist() == [5, 6]

## Индексация

Подробное описание: https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html

In [405]:
x = np.arange(20).reshape(4, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Простая индексация:

In [406]:
x[1]

array([5, 6, 7, 8, 9])

Для массивов можно делать slicing, как и для списков. По каждой размерности может быть свой slice.

x[0] эквивалентно x[0, :], то есть недостающие индексы заменяются на :

In [407]:
x[0:3, ::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

**Это интересно.** Важное отличие от питоновских списков: при slicing возвращается **view**, а не копия! Это позволяет присваивать значения подматрицам.

#### Сложная индексация

По каждой размерности подаются массивы одинаковых размеров, элементы которых соответствуют индексам каждой размерности. Тогда, на выходе будет массив размера этих массивов, элементы которого будут соответствовать элементам исходного массива, взятых в точках, соответствующих поданным массивам.

In [408]:
X = np.array([[1, 2, 3], [4, 5, 6]])
X

array([[1, 2, 3],
       [4, 5, 6]])

In [409]:
X[[0, 1], [1, 2]]

array([2, 6])

In [410]:
X[[0, 0], [1, 0]]

array([2, 1])

**Сокращенная индексация**

Если у вас есть многомерный массив, а вам, например, надо взять определенные индексы только с последней размерности, то можно написать так:

In [60]:
x = np.arange(80).reshape((2, 2, 4, 5))

In [71]:
x[..., 0]

array([[[ 0,  5, 10, 15],
        [20, 25, 30, 35]],

       [[40, 45, 50, 55],
        [60, 65, 70, 75]]])

In [69]:
x[..., 0].shape

(2, 2, 4)

## View и копирование

In [47]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
y = x
y.shape = (2, 5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

View ссылается на те же данные, но позволяет задать другие размерности массива.

In [49]:
x = np.arange(10)
v = x.view()
v.shape = (2, 5)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
v[0, 0] = 100
x

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

Если нужно получить копию массива, чтобы не портить переданные данные, пользуйтесь функцией copy()

In [51]:
x = np.arange(10)
y = x.copy()
y[:] = 0
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Разные задачи

<font color='brown'> **Задача 8.** Дана матрица размерности $N \times K$, $N$ - число объектов, $K$ - число признаков.
Подсчитать выборочное среднее и ковариационную матрицу без использования
функций mean и cov.

$$ E[X]={\frac {1}{n}}\sum \limits _{i=1}^{n}x_{i} $$

$$ {\mathrm  {cov}}(X_{{(n)}},Y_{{(n)}})={\frac  1n}\sum _{{t=1}}^{n}\left(X_{t}-\overline {X}\right)\left(Y_{t}-\overline {Y}\right)$$

 </font>

In [73]:
X = np.arange(32).reshape(8, 4)

In [ ]:
## your code

Проверьте себя:

In [453]:
assert mean.tolist() == [14, 15, 16, 17]
assert np.all(cov == 84)

<font color='brown'> **Задача 9.** Замените все максимальные элементы матрицы $A$ на 0. </font>

In [511]:
A = np.array([
    [1, 6, 3],
    [6, 2, 1],
    [4, 5, 6],
    [1, 2, 1],
])

In [512]:
## your code

In [525]:
new_A = np.array([
    [1, 0, 3],
    [0, 2, 1],
    [4, 5, 0],
    [1, 2, 1],
])
assert np.all(A == new_A)

In [97]:
## your code

<font color='brown'> **Задача 10.** Вычислить площадь четверти круга методом Монте-Карло. </font>

In [123]:
N = 1000
X = np.random.uniform(0, 1, size=(N, 2))

In [132]:
## your code

Проверьте себя:

In [128]:
np.pi / 4

0.7853981633974483

Посмотрим, как значения убывают с итерациями

In [57]:
## our code

<font color='brown'> **Задача (со звёздочкой) 11.** Даны матрицы $A$ размера $(n \times d)$ и $B$ размера $(m \times d)$. Найти в A все строки, содержащиеся в B, не используя циклы. Оцените сложность полученного алгоритма.  </font>

In [125]:
A = np.array([
    [1, 2, 3],
    [1, 2, 1],
    [4, 5, 6],
    [1, 2, 1],
    [4, 2, 1]
])

B = np.array([
    [4, 5, 6],
    [4, 5, 6],
    [1, 2, 3],
    [0, 1, 2]
])

Проверьте себя:

In [509]:
assert set(indexes) == {0, 2}

<font color='brown'> **Задача (со звёздочкой) 12.** Даны матрицы $A$ размера $(n \times d)$ и $B$ размера $(m \times d)$. Посчитайте матрицу попарных расстояний D размера $(n \times m)$ такую, что $d_{ij} = \{||a_{i} - b_{j}||\}_{i,j}^{n, m}$,  используя broadcasting. Оцените сложность полученного алгоритма. Можно ли существенно её улучшить? Подсказка: раскройте квадрат нормы разности. </font>

In [149]:
m, n, d = 5, 4, 3

A = np.random.randn(n, d)
B = np.random.randn(m, d)
A, B

(array([[-1.29599235, -1.27745093, -0.85901375],
        [ 0.3900397 ,  1.29728467,  1.25515761],
        [ 0.70165465,  0.49257793,  0.43317251],
        [-0.64788848,  1.42267242, -0.97688131]]),
 array([[-1.00535772,  0.29259359,  1.60578018],
        [ 0.94497138, -0.54210361, -0.47601677],
        [-1.58210603,  0.09617244, -2.26434635],
        [ 2.26545001,  0.26527821, -0.36274197],
        [-1.3701901 ,  1.34270407,  0.044365  ]]))

In [130]:
# your code